defaults: &defaults
  adapter: <%= RUBY_ENGINE == 'ruby' ? 'postgresql' : 'jdbcpostgresql' %>
  database: tuxedo_<%= Rails.env %>
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

cucumber:
  <<: *defaults
